config/routes.rb
Rails.application.routes.draw do
# get '/' , controller: 'home', action: 'index'  -- isso é coisa de pleno ou senior

# modo jr de fazer
root 'home#index'

# CRUD na unha pleno ou sênior!
# get '/vehicles', controller: 'vehicles', action: 'index'
# get '/vehicles/new', controller: 'vehicles', action: 'new'
# post '/vehicles', controller: 'vehicles', action: 'create'
# get '/vehicles/:id', controller: 'vehicles', action: 'show'
# get '/vehicles/:id/edit', controller: 'vehicles', action: 'edit'
# put '/vehicles/:id', controller: 'vehicles', action: 'update'
# patch '/vehicles/:id', controller: 'vehicles', action: ''
# delete '/vehicles/:id', controller: 'vehicles', action: ''

# resources :vehicles #only: [:index, :new, :create, :show, :edit, :update, :destroy]
resources :vehicles
#only: [:index, :new, :create, :show, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
   validates :brand, :model, :year, :plate, :kind, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index; end   
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
   def index
    @vehicles = Vehicle.all.order(created_at: :asc)

   end

   def new
      @vehicle = Vehicle.new
      
   end
   
   def create
      @vehicle = Vehicle.new(vehicle_params)
      
      if @vehicle.save
         redirect_to  vehicle_path(@vehicle)
      else
         render :new
      end
   end

   def show
      @vehicle = Vehicle.find(params[:id])
      
   end

   def edit
      @vehicle = Vehicle.find(params[:id])

   end

   def update
      @vehicle = Vehicle.find(params[:id])
      
      if @vehicle.update(vehicle_params)
         redirect_to  vehicle_path(@vehicle)
      else
         render :edit
      end
   end

   def destroy
      @vehicle = Vehicle.find(params[:id])

      @vehicle.destroy

      redirect_to vehicles_path
   end
   
   
   private

   def vehicle_params
      params.require(:vehicle).permit(:brand, :model, :year, :plate, :kind)
      
   end

   def fetch_vehicle
      @vehicle = Vehicle.find(params[:id])
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/edit.html.erb
<h1>Vehicles Edit</h1>

   <% if @vehicle.errors.any? %>
     <%@vehicle.errors.full_messages.each do |message| %>
      <p>
      <%= message%>
      </p>
     <% end %>
   <% end %>

<%= form_with model: @vehicle, data: { turbo: false } do |f| %>
   <p>
      <%= f.label :brand, "Brand" %>
      <%= f.text_field :brand %>
   </p>
   
   <p>
      <%= f.label :model, "Model" %>
      <%= f.text_field :model %>
   </p>
   
   <p>
      <%= f.label :year, "Year" %>
      <%= f.number_field :year %>
   </p>

   <p>
      <%= f.label :plate, "Plate" %>
      <%= f.text_field :plate %>
   </p>

   <p>
      <%= f.label :kind, "Kind" %>
      <%= f.number_field :kind %>
   </p>

   <p>
   <%= f.submit %>
   </p>

<% end %>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<p>
<%= link_to  "New Vehicle", new_vehicle_path %>
</p>

<% @vehicles.each do |vehicle| %>
      <p>
      <%= vehicle.id%> |
      <%= vehicle.brand%> |
      <%= vehicle.model%> |
      <%= vehicle.year%> |
      <%= vehicle.plate%> |
      <%= vehicle.kind%> | 
      <%= link_to  "Details", vehicle_path(vehicle) %> |
      <%= link_to  "Edit", edit_vehicle_path(vehicle) %> | 
      <%# estudar o turbo do rails 7 %>
      <%= link_to  "Erase", vehicle_path(vehicle), data: { 'turbo-method': :delete, 'turbo-confirm': 'Continuar com ação de deletar?'} %> | 

      <p>
<% end %>

app/views/vehicles/new.html.erb
<h1>Vehicles new</h1>


<%= form_with model: @vehicle, data: { turbo: false } do |f| %>
   <p>
      <%= f.label :brand, "Brand" %>
      <%= f.text_field :brand %>
   </p>
   
   <p>
      <%= f.label :model, "Model" %>
      <%= f.text_field :model %>
   </p>
   
   <p>
      <%= f.label :year, "Year" %>
      <%= f.text_field :year %>
   </p>

   <p>
      <%= f.label :plate, "Plate" %>
      <%= f.text_field :plate %>
   </p>

   <p>
      <%= f.label :kind, "Kind" %>
      <%= f.text_field :kind %>
   </p>

   <p>
   <%= f.submit %>
   </p>

<% end %>

app/views/vehicles/show.html.erb
<h1>Show Vehicle</h1>


      <p>
      <%= @vehicle.id%> |
      <%= @vehicle.brand%> |
      <%= @vehicle.model%> |
      <%= @vehicle.year%> |
      <%= @vehicle.plate%> |
      <%= @vehicle.kind%> | 
      <p>